### ISSUE TITLE
内存访问超出范围

### ISSUE THREAD

**Issue by TinkerXXX** [gogogoghost/as-crypto#2]
在使用你的md5.ts重新编写assemblyScript并生成wasm，在js中引入生成的wasm文件并调用md5.hex32()方法时，浏览器抛出异常Uncaught (in promise) RuntimeError: memory access out of bounds

我的assemblyScript代码：
import * as md5 from '../lib/md5'

function str2array(str: string): Uint8Array {
    let list = new Uint8Array(str.length);
    for (let i = 0; i < str.length; i++) {
        list[i] = str.charCodeAt(i)
    }
    return list;
}

export function sign(str: string): string {
    return md5.hex32(str2array(str));
}

请联系我，谢谢

**Comment by gogogoghost** [comment]
感谢您的反馈，我开发中使用的wasm运行环境为node，未意识到应该建立浏览器环境测试流程，我会尽快建立测试工具并确定问题。

**Comment by TinkerXXX** [comment]
如果修复该问题请与我联系，我可以请你喝一杯咖啡，我的QQ472097619 :-D

**Comment by gogogoghost** [comment]
我已在dev分支建立web测试环境，通过了较长字符串(1024000字节)运算测试，你可以通过npm run asbuild:untouched && npm run test-web来启动测试环境，你可以参考./web/index.js中的方法进行测试，如仍有问题请继续反馈

**Comment by TinkerXXX** [comment]
感谢您的帮助，我可以正常使用md5模块并且可以正常工作了！
